version: 0.2
phases:
  install:
    commands:
      - pip3 install -r requirements.txt

  build:
    commands:
      # Build the Docker image
      - docker build -t $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      # Login to ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI
      # Push the image to ECR
      - docker push $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      # - eksctl create cluster --name developer-iq --region ap-south-1 --node-type t2.micro
      # Update the kubeconfig file
      - aws eks update-kubeconfig --name developer-iq --region ap-south-1
      # Generate Kubernetes manifests
      - sed "s/TAG_PLACEHOLDER/$CODEBUILD_RESOLVED_SOURCE_VERSION/" k8configs/deployments.yml | kubectl apply -f -

# Define environment variables
env:
  variables:
    ECR_URI: 414238480542.dkr.ecr.ap-south-1.amazonaws.com/developer-iq-etl

# artifacts:
#   files:
#     # Include any artifacts you want to save
#     - build/